### ISSUE TITLE
tasks for 2016/08/07 - 2016/08/13

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla-projects/gsoc16_improved-multi-lingual#65]
Main Task for week 6 of reviewed timeline (2016/08/07 - 2016/08/13) + task to do from other weeks:
#### From previous weeks
- [x] sidebyside: Select Custom Target
- [ ] sidebyside: Implement copy feature by auto-filling fields with reference data (see also #8)
- [x] list view: Select component box. Designation based on component language string (more info #22)
- [ ] list view: [Proposal] Map relevant columns in component item model or table (more info #22)
- [x] list view: Edit target/Create a new item (article, contact, category, etc.) directly on list view (more info #22)
- [x] 3º party flexibility review after side by side + list stuff (see https://github.com/joomla-projects/gsoc16_improved-multi-lingual/issues/29)
#### From current week
- [x] Besides travis CS, needs to conform with all Joomla coding styles (XML, PHP, HTML, etc)
- [x] Component code should use the API as much as possible
- [x] Component code should reuse code as much as possible
- [x] Component needs to work with all Joomla 3.x supported db versions (mysql, postgresql, sqlazure)
- [x] Component needs to work with all Joomla 3.x supported php versions (5.3.10+)
- [x] Component needs to work with new install AND upgrade process
- [ ] Implement "wiki" page with all 3º party requirements. (see https://github.com/joomla-projects/gsoc16_improved-multi-lingual/issues/21)

**Comment by andrepereiradasilva** [comment]
@jreys 

> list view: Select component box. Designation based on component language string (more info #22)

PR https://github.com/joomla-projects/gsoc16_improved-multi-lingual/pull/72

> list view: [Proposal] Map relevant columns in component item model or table (more info #22)

PR https://github.com/joomla-projects/gsoc16_improved-multi-lingual/pull/71

> list view: Edit target/Create a new item (article, contact, category, etc.) directly on list view (more info #22)

PR https://github.com/joomla-projects/gsoc16_improved-multi-lingual/pull/69

**Comment by andrepereiradasilva** [comment]
replaced by https://github.com/joomla-projects/gsoc16_improved-multi-lingual/issues/94
