### ISSUE TITLE
tasks for 2016/08/14 - end

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla-projects/gsoc16_improved-multi-lingual#94]
Main Task for last week of reviewed timeline + task to do from other weeks:
#### From previous weeks
- [x] sidebyside: Implement copy feature by auto-filling fields with reference data (see also #8)
- [x] list view: [Proposal] Map relevant columns in component item model or table (more info #22)
- [ ] Implement "wiki" page with all 3º party requirements. (see https://github.com/joomla-projects/gsoc16_improved-multi-lingual/issues/21)
- [x] Add "Component: Item Type" title to views
- [ ] Create sidebyside-uncompressed.js
- [ ] Solve issues in github "issues"
#### From current week
- [ ] Implement "help" content.
- [x] Language strings need to be alpha ordered in ini files.
- [ ] Javascript/PHP Error catching
- [ ] Graphical and usability review
- [ ] Final tests and corrections

**Comment by jreys** [comment]
- Add title to list view

**Comment by andrepereiradasilva** [comment]
IMO this is not good we are only in 3 out 11 completed ... few days left ...
